# Site settings
title: "Euclid: The Game"
email: "bfindell@gmail.com"
description: "This website tries to gamify The Elements, a book written by Euclid."
baseurl: ""
url: "https://euclid.findell.org"

# Defaults
defaults:
    -
        scope:
            path: ""
        values:
            cat: notSorted


# Build settings
markdown: kramdown
permalink: pretty
